name: monkey_frog
channels:
  - defaults
dependencies:
  - click=8.0.1
  - ipython=7.26.0
  - matplotlib=3.4.2
  - mock=4.0.3
  - numpy=1.20.3
  - pandas=1.3.1
  - pip=21.2.2
  - python=3.8.11
  - scipy=1.6.2
  - seaborn=0.11.1
  - pip:
    - neo==0.5.2
    - quantities==0.12.4
